### ISSUE TITLE
Nice project !!

### ISSUE THREAD

**Issue by RioChndr** [gattigaga/shoryuken#21]
Nice project !. I love it. I have some request improvement

## Improvement

- delete board have no confirmation
- delete list card have no confirmation
- Some space button and form too close (ex: description form and button save)
![image](https://user-images.githubusercontent.com/22429169/178800488-390319c9-3e9a-4149-818f-d678f0bd2cc6.png)

## Nice Feature if has

It would be great if it support markdown

![image](https://user-images.githubusercontent.com/22429169/178799520-5ebed350-5ddb-4178-bcf6-1d02dda257a4.png)

**Comment by gattigaga** [comment]
Hi @RioChndr, thanks for your feedback... :smile: 
Currently I don't have time to do it...
But, I will consider your suggestion...

**Comment by gattigaga** [comment]
These features are just implemented in the new version
